# Generated by Django 4.1.5 on 2023-01-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='eventdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
