# Generated by Django 4.1.5 on 2023-01-25 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_videolinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
